#remove correlated variables
#user manually selects which layers to remove from rasterstack
#' remove variables
#'
#' A function that removes specified variables from the raster stack of climate variables
#' @param raster_stack A raster stack generated by the get_world_clim function
#' @param variables_to_be_removed A list of variables selected by the user
#' @examples
#' remove_corr_variables(raster_stack, c("bio1", "bio4", "bio10"))
remove_corr_variables <- function(environment_data, variables_to_be_removed) {

  if (missing(environment_data) || is.null(environment_data)) {
    stop("environment_data is missing or NULL")
  }
  if (missing(variables_to_be_removed) || length(variables_to_be_removed) == 0) {
    stop("variables_to_be_removed is missing or empty")
  }

  # ---- terra::SpatRaster (preferred) ----
  if (inherits(environment_data, "SpatRaster")) {

    # Support either names (character) or indices (numeric/integer)
    if (is.numeric(variables_to_be_removed)) {
      idx_drop <- unique(as.integer(variables_to_be_removed))
      idx_drop <- idx_drop[idx_drop >= 1 & idx_drop <= terra::nlyr(environment_data)]
      if (length(idx_drop) == 0) {
        warning("No valid indices to remove; returning input unchanged")
        return(environment_data)
      }

      keep_idx <- setdiff(seq_len(terra::nlyr(environment_data)), idx_drop)
      if (length(keep_idx) == 0) {
        stop("All layers would be removed; check variables_to_be_removed")
      }
      return(environment_data[[keep_idx]])

    } else {
      vars_drop <- unique(as.character(variables_to_be_removed))
      present <- intersect(names(environment_data), vars_drop)
      missing_vars <- setdiff(vars_drop, names(environment_data))
      if (length(missing_vars) > 0) {
        warning("These variables were not found and will be ignored: ", paste(missing_vars, collapse = ", "))
      }
      if (length(present) == 0) {
        warning("None of the requested variables were found; returning input unchanged")
        return(environment_data)
      }

      keep_names <- setdiff(names(environment_data), present)
      if (length(keep_names) == 0) {
        stop("All layers would be removed; check variables_to_be_removed")
      }
      return(environment_data[[keep_names]])
    }
  }

  # ---- legacy raster::Raster* ----
  if (inherits(environment_data, c("RasterStack", "RasterBrick", "RasterLayer"))) {
    if (!requireNamespace("raster", quietly = TRUE)) {
      stop("Package 'raster' is required for Raster* inputs. Install it or convert to terra::SpatRaster.")
    }

    layer_names <- names(environment_data)

    if (is.numeric(variables_to_be_removed)) {
      idx_drop <- unique(as.integer(variables_to_be_removed))
      idx_drop <- idx_drop[idx_drop >= 1 & idx_drop <= raster::nlayers(environment_data)]
      if (length(idx_drop) == 0) {
        warning("No valid indices to remove; returning input unchanged")
        return(environment_data)
      }
      return(raster::dropLayer(environment_data, idx_drop))

    } else {
      vars_drop <- unique(as.character(variables_to_be_removed))
      idx_drop <- match(vars_drop, layer_names)
      idx_drop <- idx_drop[!is.na(idx_drop)]
      missing_vars <- setdiff(vars_drop, layer_names)
      if (length(missing_vars) > 0) {
        warning("These variables were not found and will be ignored: ", paste(missing_vars, collapse = ", "))
      }
      if (length(idx_drop) == 0) {
        warning("None of the requested variables were found; returning input unchanged")
        return(environment_data)
      }
      return(raster::dropLayer(environment_data, idx_drop))
    }
  }

  stop("Unsupported input type. Provide a terra::SpatRaster or raster::RasterStack/RasterBrick.")
}
